### ISSUE TITLE
Bandit Bases: Respawn timer too short

### ISSUE THREAD

**Issue by dephelis** [jabberzac/Overthrow#40]
I spectators a fight between NATO and a bandit camp near one of the towns with low NATO control last night. After waiting for the NATO troops to withdraw, I moved in to loot the camp. I was about halfway through looting the corpses, when a fresh group of bandits spawned along with a NATO crewman.

This seems like too small a window, I would have thought that the bandits should take a day or two of in game time to regroup at the base following being wiped out.

It might also be good for the bandits to travel to the base, much like the NATO troops do, rather than just respawning directly there. What about spawning them in a boat offshore and having them land nearby or having them travel from other bases?

Version: 0.5.5
Mode: Single player

**Comment by armazac** [comment]
HI @dephelis thanks for the report! What you witnessed was actually a gang leader spawning to move into a town. The camps don't actually respawn at all. It sounds like the bug is actually that it didn't mark the camp as cleared when the camp's leader died (or maybe he got away?).

As for the NATO crewman that's not possible, he must have fallen from a helicopter.

**Comment by dephelis** [comment]
Hey @ARMAzac, sorry yes by camp I meant the bandit troops at the camp location.

It's possible that the leader got away from the trooos, the foliage of Tanoa does make it a little bit difficult to keep track of the targets! Either way there shiuld probably be a delay before he gets reinforcements!

Definitely no helicopter or NATO vehicles shot down/disabled though. I was there for the whole engagement.

**Comment by armazac** [comment]
Yep I'll look into some options and leave this issue open :)
