### ISSUE TITLE
Game no longer "persistent saves" 

### ISSUE THREAD

**Issue by stormoffires** [jabberzac/Overthrow#89]
just watched 200k and 4hrs of work go down the drain... lots of saving or so i thought but when i tried to reload it just now it went back to an older save. so i played for 20 mins, tried saving and launching again but did it still did not save that 20mins worth of work.

**Comment by foofski** [comment]
Hi,

Please upload an RPT file (on discord or via pastebin) from you server that covers the interval where persistent save failed the first time.

**Comment by stormoffires** [comment]
[arma3server_2016-12-29_19-17-55.rpt.txt](https://github.com/jabberzac/Overthrow/files/678283/arma3server_2016-12-29_19-17-55.rpt.txt)

restarted mission, tried to load, place an item, save and load.. did not work

**Comment by foofski** [comment]
> 19:27:13 Error in expression <ms ["_owner","_cls","_group"];
if(count units _group == 0) then {_do = false};
i>
19:27:13   Error position: <units _group == 0) then {_do = false};
i>
19:27:13   Error units: Type String, expected Object,Group
19:27:13 File ot\campaign\missions\Overthrow.Tanoa\actions\saveGame.sqf, line 95

This seems to be an issue specific to your current save/play-through (i.e. caused by some unknown factor, as persistent save is generally working). There's nothing in the log to explain the cause of your specific problem, but we will keep an eye out for this in testing. (yay beta-versions!)
